[package]
name = "cplex-rs-sys"
version = "0.1.0"
edition = "2021"
description = "FFI bindings to cplex"
license = "MIT"
keywords = ["optimization", "binding", "cplex"]
links = "static=cplex"

[dependencies]

[build-dependencies]
bindgen = "0.69"
glob = "0.3"

[dev-dependencies]
libc = "0.2"
