name: Rust

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["**.rs", "Cargo.toml", ".github/ci.yml"]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mbiggio/private/cplex:latest
      credentials:
          username: ${{ secrets.docker_hub_username}}
          password: ${{ secrets.docker_hub_password}}

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Build
        run: cargo build --all-features --tests
      - name: Test
        run: cargo test