name: publish-pipeline

on:
    push:
      tags:
        - v*

env:
    CARGO_TERM_COLOR: always
    CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mbiggio/cplex_community_edition:latest
      credentials:
          username: ${{ secrets.docker_hub_username}}
          password: ${{ secrets.docker_hub_password}}

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo publish